SELECT apellido1 FROM empleado;
SELECT DISTINCT apellido1 FROM empleado;
SELECT * FROM empleado;
SELECT nombre, apellido1, apellido2 FROM empleado;
SELECT codigo_departamento FROM empleado;
SELECT DISTINCT codigo_departamento FROM empleado;
SELECT CONCAT(nombre," ",apellido1," ",apellido2) AS nombre_completo FROM empleado;
SELECT UPPER(CONCAT(nombre," ",apellido1," ",apellido2)) AS nombre_completo FROM empleado;
SELECT LOWER(CONCAT(nombre," ",apellido1," ",apellido2)) AS nombre_completo FROM empleado;
SELECT codigo,  SUBSTRING(nif, 1, LENGTH(nif)-1) AS 'Digitos NIF', SUBSTRING(nif, LENGTH(nif), 1) AS 'Letra NIF' FROM empleado;
SELECT nombre, presupuesto-gastos AS presupuesto_actual FROM departamento;
SELECT nombre, presupuesto-gastos AS presupuesto_actual FROM departamento ORDER BY presupuesto_actual ASC;
SELECT nombre FROM departamento ORDER BY nombre ASC;
SELECT nombre FROM departamento ORDER BY nombre DESC;
SELECT apellido1, apellido2, nombre FROM empleado ORDER BY apellido1, apellido2, nombre DESC;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto DESC LIMIT 3;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto ASC LIMIT 3;
SELECT nombre, gastos FROM departamento ORDER BY gastos DESC LIMIT 2;
SELECT nombre, gastos FROM departamento ORDER BY gastos ASC LIMIT 2;
select * from empleado limit 5 offset 2;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto >= 150000;
SELECT nombre, gastos FROM departamento WHERE gastos < 5000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto >100000 AND presupuesto < 200000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto <= 100000 OR presupuesto >= 200000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto BETWEEN 100000 AND 200000;
SELECT nombre, presupuesto FROM departamento WHERE presupuesto NOT BETWEEN 100000 AND 200000;
SELECT nombre, presupuesto , gastos FROM departamento WHERE gastos > presupuesto;
SELECT nombre, presupuesto , gastos FROM departamento WHERE gastos < presupuesto;
SELECT nombre, presupuesto , gastos FROM departamento WHERE gastos = presupuesto;
SELECT * FROM empleado WHERE apellido2 IS NULL;
SELECT * FROM empleado WHERE apellido2 IS NOT NULL;
SELECT * FROM empleado WHERE apellido2 = 'lópez';
SELECT * FROM empleado WHERE apellido2 = 'Díaz' OR apellido2 = 'Moreno';
SELECT * FROM empleado WHERE apellido2 IN ('Díaz' , 'Moreno');
SELECT nombre, apellido1, apellido2, nif FROM empleado WHERE codigo_departamento = 3;
SELECT nombre, apellido1, apellido2, nif FROM empleado WHERE codigo_departamento IN(2, 4, 5);
SELECT empleado.nombre, departamento.codigo,departamento.nombre, presupuesto,gastos FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo;
SELECT empleado.nombre, departamento.codigo,departamento.nombre, presupuesto,gastos FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo ORDER BY departamento.nombre, apellido1, apellido2, empleado.nombre ASC;
SELECT DISTINCT departamento.codigo,departamento.nombre FROM departamento LEFT JOIN empleado ON codigo_departamento = departamento.codigo WHERE codigo_departamento IS NOT NULL;
SELECT DISTINCT departamento.codigo, departamento.nombre, presupuesto-gastos AS presupuesto_actual FROM departamento INNER JOIN empleado ON codigo_departamento = departamento.codigo WHERE codigo_departamento IS NOT NULL;
SELECT departamento.nombre FROM departamento LEFT JOIN empleado ON codigo_departamento = departamento.codigo WHERE nif = '38382980M';
SELECT departamento.nombre FROM departamento LEFT JOIN empleado ON codigo_departamento = departamento.codigo WHERE empleado.nombre ='Pepe' AND apellido1 = 'Ruiz' AND apellido2 ='Santana';
SELECT * FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo WHERE departamento.nombre = 'I+D' ORDER BY empleado.nombre ASC;
SELECT * FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo WHERE departamento.nombre IN ('Sistemas', 'Contabilidad', 'I+D') ORDER BY empleado.nombre ASC;
SELECT empleado.nombre FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo WHERE presupuesto NOT BETWEEN 100000 AND 200000;
SELECT  DISTINCT departamento.nombre FROM departamento INNER JOIN empleado ON codigo_departamento = departamento.codigo WHERE apellido2 IS NULL;
SELECT  empleado.nombre AS empleado, departamento.nombre AS departamento FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo;
SELECT  empleado.nombre AS empleado, departamento.nombre AS departamento FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo WHERE departamento.nombre IS NULL;
SELECT  departamento.nombre AS departamento, empleado.nombre AS empleado FROM departamento LEFT JOIN empleado ON codigo_departamento = departamento.codigo WHERE empleado.nombre IS NULL;
((select e1.codigo as 'Codigo Empleado', e1.nombre as 'Nombre Empleado', d1.codigo as 'Codigo Departamento', d1.nombre as 'Nombre Departamento' from empleado e1 left join departamento d1 on e1.codigo_departamento=d1.codigo or d1.codigo is null)
union
(select null as 'Codigo Empleado', null as 'Nombre Empleado', d2.codigo as 'Codigo Departamento', d2.nombre as 'Nombre Departamento' from departamento d2 left join empleado e2 on e2.codigo_departamento=d2.codigo where not exists (select * from empleado e3 where e3.codigo_departamento=d2.codigo))) order by 'Nombre Departamento';

(select e1.codigo as 'Codigo Empleado', e1.nombre as 'Nombre Empleado', d1.codigo as 'Codigo Departamento', d1.nombre as 'Nombre Departamento' from empleado e1 left join departamento d1 on e1.codigo_departamento=d1.codigo where not exists (select * from departamento d3 where e1.codigo_departamento=d3.codigo))
union
(select null as 'Codigo Empleado', null as 'Nombre Empleado', d2.codigo as 'Codigo Departamento', d2.nombre as 'Nombre Departamento' from departamento d2 left join empleado e2 on e2.codigo_departamento=d2.codigo where not exists (select * from empleado e3 where e3.codigo_departamento=d2.codigo));
SELECT SUM(presupuesto) FROM departamento;
SELECT AVG(presupuesto) FROM departamento;
SELECT MIN(presupuesto) FROM departamento;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto DESC LIMIT 1;
SELECT MAX(presupuesto) FROM departamento;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto ASC LIMIT 1;
SELECT COUNT(nombre) FROM empleado;
SELECT COUNT(nombre) FROM empleado WHERE apellido2 IS NOT NULL;
SELECT codigo_departamento, COUNT(nombre) AS numero_empleado FROM empleado GROUP BY codigo_departamento;
SELECT codigo_departamento, COUNT(nombre) AS numero_empleado FROM empleado GROUP BY codigo_departamento HAVING numero_empleado>2;
SELECT codigo_departamento, departamento.nombre, COUNT(empleado.nombre) AS numero_empleado FROM empleado LEFT JOIN departamento ON codigo_departamento = departamento.codigo GROUP BY codigo_departamento;
SELECT COUNT(empleado.nombre) AS numero_empleado FROM empleado INNER JOIN departamento ON codigo_departamento = departamento.codigo WHERE presupuesto>200000;
SELECT empleado.nombre FROM empleado, departamento WHERE departamento.nombre = "Sistemas" AND codigo_departamento = departamento.codigo;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto DESC LIMIT 1;
SELECT nombre, presupuesto FROM departamento ORDER BY presupuesto ASC LIMIT 1;
SELECT nombre, presupuesto FROM departamento d1 WHERE d1.presupuesto >= ALL (SELECT d2.presupuesto FROM departamento d2 WHERE d2.codigo <>d1.codigo);
SELECT nombre, presupuesto FROM departamento d1 WHERE d1.presupuesto <= ALL (SELECT d2.presupuesto FROM departamento d2 WHERE d2.codigo <>d1.codigo);
SELECT nombre FROM departamento WHERE codigo = ANY (SELECT codigo_departamento FROM empleado WHERE codigo_departamento = departamento.codigo);
SELECT nombre FROM departamento WHERE codigo != ALL (SELECT codigo_departamento FROM empleado WHERE codigo_departamento = departamento.codigo);
SELECT nombre FROM departamento WHERE codigo IN (SELECT codigo_departamento FROM empleado WHERE codigo_departamento = departamento.codigo);
SELECT nombre FROM departamento WHERE codigo NOT IN (SELECT codigo_departamento FROM empleado WHERE codigo_departamento = departamento.codigo);
SELECT nombre FROM departamento WHERE EXISTS  (SELECT codigo_departamento FROM empleado WHERE codigo_departamento = departamento.codigo);
SELECT nombre FROM departamento WHERE NOT EXISTS  (SELECT codigo_departamento FROM empleado WHERE codigo_departamento = departamento.codigo);