SELECT * FROM pedido ORDER BY fecha;
SELECT * FROM pedido ORDER BY total DESC LIMIT 1;
SELECT DISTINCT id_cliente FROM pedido;
SELECT * FROM pedido WHERE fecha LIKE '2017%';
SELECT nombre, apellido1, apellido2 FROM comercial WHERE comisión BETWEEN 0.05 AND 0.11;
SELECT MAX(comisión) FROM comercial;
SELECT id,nombre,apellido1 FROM cliente WHERE apellido2 IS NOT NULL ORDER BY apellido1 ASC,apellido2 ASC,nombre ASC;
SELECT nombre FROM cliente WHERE nombre LIKE  'A%n' OR nombre LIKE 'P%';
SELECT nombre FROM cliente WHERE nombre NOT LIKE 'A%' ORDER BY nombre ASC;
SELECT DISTINCT nombre FROM comercial WHERE nombre LIKE '%el' OR  nombre Like '%o' ORDER BY nombre ASC;
SELECT DISTINCT cliente.id,nombre,apellido1,apellido2 FROM cliente INNER JOIN pedido ON cliente.id =pedido.id_cliente;
SELECT * FROM pedido INNER JOIN cliente ON cliente.id =pedido.id_cliente ORDER BY cliente.nombre ASC;
SELECT * FROM pedido INNER JOIN comercial ON comercial.id =pedido.id_comercial ORDER BY comercial.nombre ASC;
SELECT * FROM cliente cl1 JOIN pedido p1 ON cl1.id =p1.id_cliente JOIN comercial c1 ON c1.id =p1.id_comercial;
SELECT cliente.nombre FROM cliente INNER JOIN pedido ON cliente.id =pedido.id_cliente WHERE fecha LIKE '2017%' AND total BETWEEN 300 AND 1000;
SELECT DISTINCT c1.nombre, c1.apellido1, c1.apellido2 FROM comercial c1 INNER JOIN pedido p1 ON c1.id =p1.id_comercial INNER JOIN cliente cl1 ON cl1.id =p1.id_cliente WHERE cl1.nombre = 'María' AND cl1.apellido1= 'Santana' AND cl1.apellido2= 'Moreno';
SELECT cl1.nombre FROM cliente cl1 INNER JOIN pedido p1 ON cl1.id =p1.id_cliente INNER JOIN comercial c1 ON c1.id =p1.id_comercial WHERE  c1.nombre = 'Daniel' AND c1.apellido1= 'Sáez' AND c1.apellido2= 'Vega';
SELECT * FROM cliente LEFT JOIN pedido ON cliente.id =pedido.id_cliente ORDER BY cliente.nombre ASC, cliente.apellido1 ASC, cliente.apellido2 ASC;
SELECT * FROM comercial LEFT JOIN pedido ON comercial.id =pedido.id_comercial ORDER BY comercial.nombre ASC, comercial.apellido1 ASC, comercial.apellido2 ASC;
SELECT * FROM cliente LEFT JOIN pedido ON cliente.id =pedido.id_cliente WHERE total IS NULL;
SELECT * FROM comercial LEFT JOIN pedido ON comercial.id =pedido.id_comercial WHERE total IS NULL;
SELECT cl1.nombre AS cliente_nombre, cl1.apellido1 AS cliente_apellido1, cl1.apellido2 AS cliente_apellido2, c1.nombre AS comercial_nombre, c1.apellido1 AS comercial_apellido1, c1.apellido2 AS comercial_apellido2 FROM cliente cl1 INNER JOIN pedido p1 ON cl1.id =p1.id_cliente INNER JOIN comercial c1 ON c1.id =p1.id_comercial WHERE total IS NULL;
select cl.apellido1, cl.apellido2, cl.nombre from cliente cl left join pedido p on cl.id=p.id_cliente where p.id_cliente is null order by cl.apellido1, cl.apellido2, cl.nombre asc;
select * from pedido;
SELECT  SUM(total) FROM pedido;
SELECT  AVG(total) FROM pedido;
SELECT  COUNT(DISTINCT id_comercial) FROM pedido;
SELECT  COUNT(id) FROM cliente;
SELECT  MAX(total) FROM pedido;
SELECT  MIN(total) FROM pedido;
SELECT ciudad, MAX(categoría) FROM cliente GROUP BY ciudad;
SELECT cliente.id, nombre,apellido1,apellido2,fecha,Max(total) FROM cliente INNER JOIN pedido ON cliente.id =pedido.id_cliente GROUP BY cliente.id;
SELECT MAX(total), id_cliente FROM pedido WHERE total > 2000 GROUP BY id_cliente;
SELECT comercial.id, nombre,apellido1,apellido2,Max(total) FROM comercial INNER JOIN pedido ON comercial.id =pedido.id_cliente GROUP BY comercial.id HAVING fecha = '2016-08-17';
SELECT cliente.id, nombre,apellido1,apellido2,SUM(total) FROM cliente LEFT JOIN pedido ON cliente.id =pedido.id_cliente GROUP BY cliente.id;
SELECT cliente.id, nombre,apellido1,apellido2,SUM(total) FROM cliente LEFT JOIN pedido ON cliente.id =pedido.id_cliente AND fecha LIKE '2017%' GROUP BY cliente.id;
SELECT cliente.id, nombre,apellido1,apellido2, IFNULL(SUM(total),0) FROM cliente LEFT JOIN pedido ON cliente.id =pedido.id_cliente GROUP BY cliente.id;
SELECT YEAR(fecha), MAX(total) FROM pedido GROUP BY YEAR(fecha) ORDER BY YEAR(fecha) ASC;
SELECT * FROM pedido WHERE id_cliente = (SELECT id FROM cliente WHERE nombre ="Adela" AND apellido1= "Salas" AND apellido2="Díaz");
SELECT COUNT(id) FROM pedido WHERE id_comercial = (SELECT id FROM comercial WHERE nombre ='Daniel' AND apellido1= 'Sáez' AND apellido2='Vega');
SELECT * FROM cliente WHERE id =(SELECT id_cliente FROM pedido WHERE YEAR(fecha)=2019 ORDER BY total DESC limit 1);
SELECT fecha, total FROM pedido WHERE id_cliente = (SELECT id FROM cliente WHERE nombre ='Pepe' AND apellido1= 'Ruiz' AND apellido2='Santana');
SELECT * FROM cliente INNER JOIN pedido ON cliente.id =pedido.id_cliente WHERE YEAR(fecha)=2017 AND total >= (SELECT AVG(total) FROM pedido);
SELECT * FROM pedido p1 WHERE p1.total > ALL (SELECT p2.total FROM pedido p2 WHERE p2.id <>p1.id);
SELECT * FROM cliente WHERE id != ALL(SELECT id_cliente FROM pedido);
SELECT * FROM comercial WHERE id != ALL(SELECT id_comercial FROM pedido);
SELECT * FROM cliente WHERE id NOT IN (SELECT id_cliente FROM pedido);
SELECT * FROM comercial WHERE id NOT IN (SELECT id_comercial FROM pedido);
SELECT * FROM cliente WHERE NOT EXISTS (SELECT id_cliente FROM pedido WHERE cliente.id =pedido.id_cliente );
SELECT * FROM comercial WHERE NOT EXISTS (SELECT id_comercial FROM pedido WHERE comercial.id =pedido.id_comercial);