SELECT codigo_oficina, ciudad FROM oficina;
SELECT ciudad,telefono FROM oficina WHERE pais='España';
SELECT nombre, apellido1, apellido2, email FROM empleado WHERE codigo_empleado = 7;
SELECT puesto, nombre, apellido1, apellido2, email FROM empleado WHERE puesto LIKE 'Directo%';
SELECT nombre, apellido1, apellido2, puesto FROM empleado WHERE puesto !=  'Representante Ventas';
SELECT nombre_cliente FROM cliente WHERE pais = 'Spain';
SELECT DISTINCT estado FROM pedido;
SELECT codigo_cliente FROM pago WHERE YEAR(fecha_pago)=2008;
SELECT codigo_cliente FROM pago WHERE DATE_FORMAT(fecha_pago, '%Y')=2008;
SELECT codigo_cliente FROM pago WHERE fecha_pago LIKE '2008%';
SELECT codigo_pedido, codigo_cliente, fecha_esperada, fecha_entrega FROM pedido WHERE fecha_entrega IS NULL;
SELECT codigo_pedido, codigo_cliente, fecha_esperada, fecha_entrega FROM pedido WHERE DATE_ADD(fecha_entrega,INTERVAL 2 DAY) =fecha_esperada;
SELECT codigo_pedido, codigo_cliente, fecha_esperada, fecha_entrega FROM pedido WHERE DATEDIFF(fecha_esperada,fecha_entrega) = 2;
SELECT * FROM pedido WHERE estado='rechazado' AND YEAR(fecha_pedido)=2009;
SELECT * FROM pedido WHERE estado='entregado' AND MONTH(fecha_pedido)=01;
SELECT * FROM pago WHERE YEAR(fecha_pago)=2008 AND forma_pago = 'paypal' ORDER BY total DESC;
SELECT DISTINCT forma_pago FROM pago;
SELECT * FROM producto WHERE gama='Ornamentales' AND cantidad_en_stock >100 ORDER BY precio_venta DESC;
SELECT * FROM cliente WHERE ciudad ='madrid' and codigo_empleado_rep_ventas IN (11,30);
SELECT cliente.nombre_cliente, empleado.nombre, empleado.apellido1, empleado.apellido2 FROM cliente INNER JOIN empleado ON empleado.codigo_empleado=cliente.codigo_empleado_rep_ventas;
SELECT DISTINCT c.nombre_cliente, e.nombre AS nombre_rep_ventas FROM cliente c INNER JOIN pago p ON c.codigo_cliente = p.codigo_cliente INNER JOIN empleado e ON e.codigo_empleado=c.codigo_empleado_rep_ventas;
SELECT c.codigo_cliente, c.nombre_cliente, e.nombre AS nombre_rep_ventas FROM cliente c INNER JOIN empleado e ON c.codigo_empleado_rep_ventas=e.codigo_empleado WHERE NOT EXISTS (SELECT * FROM pago p WHERE p.codigo_cliente=c.codigo_cliente);
SELECT DISTINCT c.nombre_cliente, e.nombre AS nombre_rep_ventas, o.ciudad FROM cliente c INNER JOIN pago p ON c.codigo_cliente = p.codigo_cliente INNER JOIN empleado e ON e.codigo_empleado=c.codigo_empleado_rep_ventas INNER JOIN oficina o ON e.codigo_oficina = o.codigo_oficina;
SELECT c.codigo_cliente,c.nombre_cliente, e.nombre AS nombre_rep_ventas, o.ciudad FROM cliente c INNER JOIN empleado e ON e.codigo_empleado=c.codigo_empleado_rep_ventas INNER JOIN oficina o ON e.codigo_oficina = o.codigo_oficina WHERE NOT EXISTS (SELECT * FROM pago p WHERE p.codigo_cliente=c.codigo_cliente);
SELECT o.linea_direccion1, o.linea_direccion2 FROM oficina o INNER JOIN empleado e ON o.codigo_oficina = e.codigo_oficina WHERE EXISTS (SELECT * FROM cliente WHERE linea_direccion2= "Fuenlabrada" OR ciudad="Fuenlabrada");
SELECT c.nombre_cliente, e.nombre AS nombre_rep_ventas, o.ciudad FROM cliente c INNER JOIN empleado e ON c.codigo_empleado_rep_ventas = e.codigo_empleado INNER JOIN oficina o ON e.codigo_oficina = o.codigo_oficina;
SELECT e.nombre AS 'Empleado', j.nombre AS 'Jefe' FROM empleado e INNER JOIN empleado j ON e.codigo_jefe=j.codigo_empleado;
SELECT nombre_cliente FROM cliente INNER JOIN pedido ON cliente.codigo_cliente = pedido.codigo_cliente WHERE fecha_entrega IS NULL;
SELECT DISTINCT gama, codigo_cliente FROM producto pro INNER JOIN detalle_pedido de ON pro.codigo_producto = de.codigo_producto INNER JOIN pedido pe ON de.codigo_pedido=pe.codigo_pedido;
SELECT DISTINCT c.nombre_cliente FROM cliente c LEFT JOIN pago p ON c.codigo_cliente=p.codigo_cliente WHERE p.codigo_cliente IS NULL;
SELECT DISTINCT c.nombre_cliente FROM cliente c LEFT JOIN pedido p ON c.codigo_cliente=p.codigo_cliente WHERE p.codigo_cliente IS NULL;
SELECT DISTINCT c.nombre_cliente FROM cliente c LEFT JOIN pago pa ON c.codigo_cliente=pa.codigo_cliente LEFT JOIN pedido pe ON c.codigo_cliente=pe.codigo_cliente WHERE pa.codigo_cliente IS NULL AND pe.codigo_cliente IS NULL;
SELECT nombre FROM empleado LEFT JOIN oficina ON empleado.codigo_oficina = oficina.codigo_oficina WHERE oficina.codigo_oficina IS NULL;
SELECT nombre FROM empleado LEFT JOIN cliente ON empleado.codigo_empleado= cliente.codigo_empleado_rep_ventas WHERE cliente.codigo_empleado_rep_ventas IS NULL;
SELECT empleado.nombre,oficina.* FROM empleado LEFT JOIN oficina ON oficina.codigo_oficina=empleado.codigo_oficina LEFT JOIN cliente ON empleado.codigo_empleado= cliente.codigo_empleado_rep_ventas WHERE cliente.codigo_empleado_rep_ventas IS NULL;
SELECT nombre FROM empleado LEFT JOIN oficina ON empleado.codigo_oficina = oficina.codigo_oficina LEFT JOIN cliente ON empleado.codigo_empleado= cliente.codigo_empleado_rep_ventas WHERE oficina.codigo_oficina IS NULL AND cliente.codigo_empleado_rep_ventas IS NULL;
SELECT nombre FROM producto LEFT JOIN detalle_pedido ON producto.codigo_producto = detalle_pedido.codigo_producto WHERE detalle_pedido.codigo_producto IS NULL;
SELECT nombre, producto.descripcion, imagen FROM producto LEFT JOIN gama_producto ON producto.gama = gama_producto.gama LEFT JOIN detalle_pedido ON producto.codigo_producto = detalle_pedido.codigo_producto WHERE detalle_pedido.codigo_producto IS NULL;
SELECT DISTINCT codigo_oficina FROM empleado INNER JOIN cliente ON codigo_empleado=codigo_empleado_rep_ventas INNER JOIN pedido ON cliente.codigo_cliente =pedido.codigo_cliente INNER JOIN detalle_pedido ON pedido.codigo_pedido=detalle_pedido.codigo_pedido WHERE detalle_pedido.codigo_pedido NOT IN(SELECT gama FROM producto WHERE gama='Frutales');
SELECT DISTINCT c.nombre_cliente FROM cliente c LEFT JOIN pago pa ON c.codigo_cliente=pa.codigo_cliente LEFT JOIN pedido pe ON c.codigo_cliente=pe.codigo_cliente WHERE pa.codigo_cliente IS NULL;
SELECT e.nombre AS 'Empleado', j.nombre AS 'Jefe' FROM empleado e INNER JOIN empleado j ON e.codigo_jefe=j.codigo_empleado  LEFT JOIN cliente ON e.codigo_empleado= cliente.codigo_empleado_rep_ventas WHERE cliente.codigo_empleado_rep_ventas IS NULL;
SELECT COUNT(codigo_empleado) FROM empleado;
SELECT COUNT(codigo_cliente) FROM cliente GROUP BY pais;
SELECT AVG(total) FROM pago WHERE fecha_pago LIKE '2009%';
SELECT COUNT(codigo_pedido) FROM pedido GROUP BY estado ORDER BY COUNT(codigo_pedido) DESC;
SELECT MAX(precio_venta), MIN(precio_venta) FROM producto;
SELECT COUNT(codigo_cliente) FROM cliente;
SELECT COUNT(codigo_cliente) FROM cliente WHERE ciudad = 'madrid';
SELECT ciudad,COUNT(codigo_cliente) FROM cliente WHERE ciudad LIKE 'm%' GROUP BY ciudad;
SELECT nombre,COUNT(nombre_cliente) FROM empleado LEFT JOIN cliente ON empleado.codigo_empleado=cliente.codigo_empleado_rep_ventas GROUP BY nombre;
SELECT COUNT(codigo_cliente) FROM cliente WHERE codigo_empleado_rep_ventas IS NULL;
SELECT pago.codigo_cliente, cliente.nombre_cliente, max(fecha_pago), min(fecha_pago) FROM pago LEFT JOIN cliente ON cliente.codigo_cliente = pago.codigo_cliente GROUP BY pago.codigo_cliente;
SELECT codigo_pedido,COUNT(producto.codigo_producto) FROM detalle_pedido INNER JOIN producto ON detalle_pedido.codigo_producto = producto.codigo_producto GROUP BY codigo_pedido;
SELECT codigo_pedido, sum(cantidad) FROM detalle_pedido GROUP BY codigo_pedido;
SELECT codigo_producto,cantidad FROM detalle_pedido ORDER BY cantidad DESC LIMIT 20;
SELECT SUM(cantidad*precio_unidad) AS base, SUM(cantidad*precio_unidad) *0.21 AS IVA, SUM(cantidad*precio_unidad)+SUM(cantidad*precio_unidad)*0.21 AS total FROM detalle_pedido;
SELECT codigo_producto, SUM(cantidad*precio_unidad) AS base, SUM(cantidad*precio_unidad) *0.21 AS IVA, SUM(cantidad*precio_unidad)+SUM(cantidad*precio_unidad)*0.21 AS total FROM detalle_pedido GROUP BY codigo_producto;
SELECT codigo_producto, SUM(cantidad*precio_unidad) AS base, SUM(cantidad*precio_unidad) *0.21 AS IVA, SUM(cantidad*precio_unidad)+SUM(cantidad*precio_unidad)*0.21 AS total FROM detalle_pedido GROUP BY codigo_producto HAVING codigo_producto LIKE 'OR%';
SELECT nombre AS Nombre, SUM(cantidad) AS 'Unidades Vendidas', SUM(cantidad*precio_unidad) AS 'Total Facturado', SUM(cantidad*precio_unidad)+SUM(cantidad*precio_unidad)*0.21 AS 'Total Facturado Con Impuestos' FROM detalle_pedido LEFT JOIN producto ON detalle_pedido.codigo_producto = producto.codigo_producto GROUP BY detalle_pedido.codigo_producto HAVING SUM(cantidad*precio_unidad)>3000;
SELECT nombre_cliente, limite_credito FROM cliente ORDER BY limite_credito DESC LIMIT 1;
SELECT nombre, precio_venta FROM producto ORDER BY precio_venta DESC LIMIT 1;
SELECT nombre FROM producto INNER JOIN detalle_pedido ON producto.codigo_producto=detalle_pedido.codigo_producto GROUP BY nombre ORDER BY SUM(cantidad) limit 1;
SELECT nombre_cliente FROM cliente WHERE limite_credito > (SELECT SUM(total) FROM pago WHERE cliente.codigo_cliente=pago.codigo_cliente GROUP BY codigo_cliente);
SELECT nombre, MAX(cantidad_en_stock) FROM producto GROUP BY nombre;
SELECT nombre, cantidad_en_stock FROM producto ORDER BY cantidad_en_stock DESC limit 1;
SELECT nombre, cantidad_en_stock FROM producto ORDER BY cantidad_en_stock ASC limit 1;
SELECT e1.nombre, e1.apellido1 FROM empleado e1 WHERE e1.codigo_empleado = (SELECT e2.codigo_jefe FROM empleado e2 WHERE e2.nombre ='Alberto' AND e2.apellido1='Soria');
SELECT nombre_cliente FROM cliente c1 WHERE c1.limite_credito > ALL (SELECT c2.limite_credito FROM cliente c2 WHERE c2.codigo_cliente <>c1.codigo_cliente);
SELECT nombre FROM producto p1 WHERE p1.precio_venta > ALL (SELECT p2.precio_venta FROM producto p2 WHERE p2.codigo_producto <>p1.codigo_producto);
SELECT * FROM producto p1 WHERE p1.cantidad_en_stock < ALL (SELECT p2.cantidad_en_stock FROM producto p2 WHERE p2.codigo_producto <>p1.codigo_producto);
SELECT nombre, apellido1, puesto FROM empleado WHERE codigo_empleado NOT IN (SELECT codigo_empleado_rep_ventas FROM cliente);
SELECT * FROM cliente WHERE codigo_cliente NOT IN (SELECT codigo_cliente FROM pago);
SELECT * FROM cliente WHERE codigo_cliente IN (SELECT codigo_cliente FROM pago);
SELECT * FROM producto WHERE codigo_producto NOT IN (SELECT codigo_producto FROM detalle_pedido);
SELECT nombre, apellido1, apellido2, puesto, telefono FROM empleado INNER JOIN oficina ON empleado.codigo_oficina=oficina.codigo_oficina WHERE codigo_empleado NOT IN (SELECT codigo_empleado_rep_ventas FROM cliente);
SELECT DISTINCT codigo_oficina FROM empleado INNER JOIN cliente ON codigo_empleado=codigo_empleado_rep_ventas INNER JOIN pedido ON cliente.codigo_cliente =pedido.codigo_cliente INNER JOIN detalle_pedido ON pedido.codigo_pedido=detalle_pedido.codigo_pedido WHERE detalle_pedido.codigo_pedido NOT IN(SELECT gama FROM producto WHERE gama='Frutales');
SELECT * FROM cliente WHERE codigo_cliente NOT IN (SELECT codigo_cliente FROM pago) AND codigo_cliente IN (SELECT codigo_cliente FROM pedido);
SELECT * FROM cliente WHERE NOT EXISTS (SELECT codigo_cliente FROM pago WHERE cliente.codigo_cliente=pago.codigo_cliente);
SELECT * FROM cliente WHERE EXISTS (SELECT codigo_cliente FROM pago WHERE cliente.codigo_cliente=pago.codigo_cliente);
SELECT * FROM producto WHERE NOT EXISTS (SELECT codigo_producto FROM detalle_pedido WHERE detalle_pedido.codigo_producto=producto.codigo_producto);
SELECT * FROM producto WHERE EXISTS (SELECT codigo_producto FROM detalle_pedido WHERE detalle_pedido.codigo_producto=producto.codigo_producto);
SELECT nombre_cliente, COUNT(codigo_pedido) FROM cliente LEFT JOIN pedido ON cliente.codigo_cliente=pedido.codigo_cliente GROUP BY nombre_cliente;
SELECT nombre_cliente, SUM(total) FROM cliente LEFT JOIN pago ON cliente.codigo_cliente=pago.codigo_cliente GROUP BY nombre_cliente;
SELECT DISTINCT nombre_cliente FROM cliente INNER JOIN pedido ON cliente.codigo_cliente=pedido.codigo_cliente WHERE fecha_pedido LIKE '2008%' ORDER BY nombre_cliente ASC;
SELECT nombre_cliente, nombre, apellido1, oficina.telefono FROM empleado INNER JOIN oficina ON empleado.codigo_oficina=oficina.codigo_oficina INNER JOIN cliente ON codigo_empleado=codigo_empleado_rep_ventas WHERE codigo_cliente NOT IN (SELECT codigo_cliente FROM pago);
SELECT nombre_cliente, nombre, apellido1, oficina.ciudad FROM empleado INNER JOIN oficina ON empleado.codigo_oficina=oficina.codigo_oficina INNER JOIN cliente ON codigo_empleado=codigo_empleado_rep_ventas;
SELECT nombre, apellido1, apellido2, puesto, telefono FROM empleado  INNER JOIN oficina ON empleado.codigo_oficina=oficina.codigo_oficina WHERE codigo_empleado NOT IN (SELECT codigo_empleado_rep_ventas FROM cliente);
SELECT ciudad, COUNT(codigo_empleado) AS numero_empleado FROM empleado INNER JOIN oficina ON empleado.codigo_oficina=oficina.codigo_oficina GROUP BY ciudad;