SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1, apellido2, nombre ASC;
SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' AND telefono IS NULL;
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento LIKE '1999%';
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%k';
SELECT * FROM asignatura WHERE cuatrimestre=1 AND curso=3 AND id_grado=7;
SELECT * FROM persona WHERE persona.tipo = 'alumno' AND sexo = 'M' AND EXISTS (SELECT grado.nombre FROM grado  INNER JOIN asignatura ON grado.id= asignatura.id_grado INNER JOIN alumno_se_matricula_asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura WHERE grado.nombre ='Grado en Ingeniería Informática (Plan 2015)');
SELECT asignatura.nombre FROM asignatura INNER JOIN grado ON asignatura.id_grado = grado.id WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT apellido1, apellido2, persona.nombre, departamento.nombre AS nombre_departamento FROM persona INNER JOIN profesor ON profesor.id_profesor=persona.id INNER JOIN departamento ON departamento.id = profesor.id_departamento WHERE persona.tipo = 'profesor' ORDER BY apellido1, apellido2, persona.nombre ASC;
SELECT nombre, anyo_inicio, anyo_fin FROM asignatura INNER JOIN alumno_se_matricula_asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE EXISTS (SELECT id FROM persona WHERE nif ='26902806M');
SELECT DISTINCT departamento.nombre FROM departamento INNER JOIN profesor ON departamento.id = profesor.id_departamento INNER JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor INNER JOIN grado ON asignatura.id_grado = grado.id WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT persona.id,nombre FROM persona INNER JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar= curso_escolar.id WHERE anyo_inicio = 2018 AND anyo_fin = 2019;
SELECT departamento.nombre AS nombre_departamento, persona.nombre, apellido1, apellido2 FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN departamento ON departamento.id = profesor.id_departamento WHERE persona.tipo = 'profesor' ORDER BY departamento.nombre, apellido1, apellido2, persona.nombre ASC;
SELECT nombre FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id WHERE persona.tipo = 'profesor' AND id_departamento IS NULL;
SELECT * FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento WHERE id_profesor IS NULL;
SELECT * FROM profesor LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE id IS NULL;
SELECT * FROM asignatura LEFT JOIN profesor ON profesor.id_profesor = asignatura.id_profesor WHERE profesor.id_profesor IS NULL;
SELECT DISTINCT departamento.nombre FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor LEFT JOIN alumno_se_matricula_asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura LEFT JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.id IS NULL;
SELECT COUNT(id) AS numero_alumna FROM persona WHERE tipo = 'alumno' AND sexo = 'm';
SELECT COUNT(id) AS alumno_1999 FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento LIKE '1999%';
SELECT nombre, COUNT(id_profesor) AS numero_profesor FROM profesor INNER JOIN departamento ON departamento.id = profesor.id_departamento GROUP BY nombre ORDER BY COUNT(id_profesor) DESC;
SELECT departamento.nombre AS nombre_departamento, COUNT(persona.nombre) FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN departamento ON departamento.id = profesor.id_departamento WHERE persona.tipo = 'profesor' GROUP BY departamento.nombre;
SELECT grado.nombre, COUNT(asignatura.id) AS numero_asignatura FROM grado LEFT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre ORDER BY COUNT(asignatura.id) DESC;
SELECT grado.nombre, COUNT(asignatura.id) AS numero_asignatura FROM grado LEFT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre HAVING COUNT(asignatura.id) > 40;
SELECT  DISTINCT tipo, grado.nombre, SUM(creditos) FROM asignatura left JOIN grado ON asignatura.id_grado = grado.id GROUP BY tipo, asignatura.id_grado;
SELECT anyo_inicio, COUNT(id_alumno) FROM curso_escolar LEFT JOIN alumno_se_matricula_asignatura ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar GROUP BY anyo_inicio;
SELECT persona.id, persona.nombre, apellido1, apellido2, COUNT(asignatura.id) FROM persona LEFT JOIN profesor ON profesor.id_profesor = persona.id LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE persona.tipo = 'profesor' GROUP BY persona.id ORDER BY COUNT(asignatura.id) DESC;
SELECT * FROM persona WHERE tipo = 'alumno' ORDER BY fecha_nacimiento ASC LIMIT 1;
SELECT nombre FROM persona WHERE NOT EXISTS (SELECT id_profesor FROM profesor WHERE profesor.id_profesor = persona.id);
SELECT * FROM departamento WHERE NOT EXISTS (SELECT id_departamento FROM profesor WHERE departamento.id = profesor.id_departamento);
SELECT * FROM profesor WHERE NOT EXISTS (SELECT id_profesor FROM asignatura WHERE profesor.id_profesor = asignatura.id_profesor);
SELECT * FROM asignatura WHERE NOT EXISTS(SELECT id_profesor FROM profesor WHERE  profesor.id_profesor = asignatura.id_profesor);